# Generated by Django 4.2.5 on 2023-11-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=20)),
                ('L_name', models.CharField(max_length=20)),
                ('Registration_no', models.IntegerField()),
            ],
        ),
    ]
