# Generated by Django 4.2.5 on 2023-11-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_basic',
            name='Registration_no',
            field=models.IntegerField(unique=True),
        ),
    ]
