# Generated by Django 4.2.5 on 2023-12-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_basic_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_basic',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_basic',
            name='Registration_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
